[[FastJet_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "23158ea78432e444bda53b6ff787f299954696d1"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "f84a98a15a2ab83f16da3a3b3b16c091b7a6d19ff9f653478feaa4a1e1b29587"
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.0-alpha3+0/FastJet_Julia_Wrapper.v0.8.0-alpha3.x86_64-linux-gnu.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c678d36543b6c5a2a59bb33f90722fe54f654c96"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "ee240130c7c11d600fa558e5395e9447cb479183711db893e7e65600a6ee902e"
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.2-alpha1+1/FastJet_Julia_Wrapper.v0.8.2-alpha1.x86_64-linux-gnu-cxx11.tar.gz"
