[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "427212fe800014fc15be12575b7f7cc612c31e46"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "af0710d6c01b3fe31e4c5b6a553766a32dfcf70630b00f4158b6a9d81179fdcc"
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.7.1+0/FastJet_Julia_Wrapper.v0.7.1.x86_64-linux-gnu-cxx11.tar.gz"
