[[FastJet_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "23158ea78432e444bda53b6ff787f299954696d1"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "f84a98a15a2ab83f16da3a3b3b16c091b7a6d19ff9f653478feaa4a1e1b29587"
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.0-alpha3+0/FastJet_Julia_Wrapper.v0.8.0-alpha3.x86_64-linux-gnu.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1567adbb60ee6b367f3a8fbe10f29939f869d008"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "de66cd1924f1055bfa2e3120b8c60e3cfd74438bfda0d02b686694d3dea9eac9"
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.3-alpha1+1/FastJet_Julia_Wrapper.v0.8.3-alpha1.x86_64-linux-gnu-cxx11.tar.gz"
