[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7402ea109050c4c54af3017d9ecee2465248edab"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "a245a130457255663bd8419f51d6a51a1cfde778b9783479f920cacf82f548d0"
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.7.0+0/FastJet_Julia_Wrapper.v0.7.0.x86_64-linux-gnu-cxx11.tar.gz"
