[[FastJet_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "23158ea78432e444bda53b6ff787f299954696d1"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "f84a98a15a2ab83f16da3a3b3b16c091b7a6d19ff9f653478feaa4a1e1b29587"
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.0-alpha3+0/FastJet_Julia_Wrapper.v0.8.0-alpha3.x86_64-linux-gnu.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74c6172139c44e477f2cb3599040e9696f842f51"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "63c432dd21801f8a76906b698864ee6ca25192a5d0c9f2c44677e073f6c8bdbd"
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.4-alpha1+0/FastJet_Julia_Wrapper.v0.8.4-alpha1.x86_64-linux-gnu-cxx11.tar.gz"
