[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0bf5c1bb522f28207125cd55503422952ec1e51"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "3a2f093722a53dd06f324f691111e9447150a757f20722501b313e2c9d3ea3b5"
    url = "https://github.com/jstrube/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.7.0-1+0/FastJet_Julia_Wrapper.v0.7.0-1.x86_64-linux-gnu-cxx11.tar.gz"
